name: Deploy public-api-ts

on:
  push:
    branches:
      - main
      - feat/*

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  DEPLOYMENT_BUCKET: ${{ secrets.DEPLOYMENT_BUCKET }}
  APP_ID: ${{ secrets.APP_ID }}

  DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
  CERTIFICATE_NAME: ${{ secrets.CERTIFICATE_NAME }}

  CORS_ORIGIN: ${{ secrets.CORS_ORIGIN }}

  README_SECRET: ${{ secrets.README_SECRET }}
  AWS_DEFAULT_USAGE_PLAN_ID: ${{ secrets.AWS_DEFAULT_USAGE_PLAN_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: aws
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Pre-build
      run: npm ci

    # not yet completely prepared `testable` code
    # - name: Run tests
    #   run: npm run test

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: set env
      run: |
        export ACCOUNT_ID=$(aws sts get-caller-identity | jq -r .Account);
        echo "ACCOUNT_ID=$ACCOUNT_ID" >> $GITHUB_ENV
    
    - name: testing env
      run: echo ACCOUNT_ID=${{ env.ACCOUNT_ID }}; echo "BOOM"

    - name: 'Deploying to stage: dev'
      uses: './.github/actions/sls-deploy'
      with:
        service-folder: .
        stage: dev
        aws-account-id: ${{ env.ACCOUNT_ID }}
        app-id: ${{ env.APP_ID }}
